import type { ToyWithImages, ToyCategory, ToyCondition, AgeRange } from '@toycycle/shared';

/**
 * Mock toy data for development before Supabase is connected.
 * Each toy uses the shared types from @toycycle/shared.
 */
export const MOCK_TOYS: ToyWithImages[] = [
  {
    id: '1',
    owner_id: 'user-1',
    title: '乐高城市系列 消防局 60320',
    description: '包含消防车、直升机和3个人仔。拼搭完成后拆开保存，全部配件齐全。',
    category: 'building' as ToyCategory,
    age_range: '6-9' as AgeRange,
    condition: 'like_new' as ToyCondition,
    estimated_value: 80,
    status: 'available',
    is_cleaned: true,
    latitude: 39.9042,
    longitude: 116.4074,
    created_at: '2026-05-01T10:00:00Z',
    updated_at: '2026-05-01T10:00:00Z',
    images: [{ id: 'img-1', toy_id: '1', image_url: '', display_order: 0 }],
    owner: {
      id: 'user-1',
      username: 'happy_mom',
      avatar_url: null,
      display_name: '快乐妈妈',
      latitude: 39.9042,
      longitude: 116.4074,
      location_name: '北京市朝阳区',
      credit_balance: 120,
      locale: 'zh',
      created_at: '2026-04-01T00:00:00Z',
    },
  },
  {
    id: '2',
    owner_id: 'user-2',
    title: '费雪小海马安抚玩具',
    description: '可以发光播放轻柔音乐，适合哄睡。使用过但功能正常，已清洗消毒。',
    category: 'stuffed' as ToyCategory,
    age_range: '0-1' as AgeRange,
    condition: 'used' as ToyCondition,
    estimated_value: 30,
    status: 'available',
    is_cleaned: true,
    latitude: 39.9142,
    longitude: 116.4174,
    created_at: '2026-05-02T14:00:00Z',
    updated_at: '2026-05-02T14:00:00Z',
    images: [{ id: 'img-2', toy_id: '2', image_url: '', display_order: 0 }],
    owner: {
      id: 'user-2',
      username: 'dad_zhang',
      avatar_url: null,
      display_name: '张爸爸',
      latitude: 39.9142,
      longitude: 116.4174,
      location_name: '北京市东城区',
      credit_balance: 85,
      locale: 'zh',
      created_at: '2026-04-05T00:00:00Z',
    },
  },
  {
    id: '3',
    owner_id: 'user-3',
    title: '磁力片积木 100片套装',
    description: '包含正方形、三角形、长方形等多种形状。培养空间思维和创造力。',
    category: 'educational' as ToyCategory,
    age_range: '3-6' as AgeRange,
    condition: 'like_new' as ToyCondition,
    estimated_value: 60,
    status: 'available',
    is_cleaned: true,
    latitude: 39.8942,
    longitude: 116.3974,
    created_at: '2026-05-03T09:30:00Z',
    updated_at: '2026-05-03T09:30:00Z',
    images: [{ id: 'img-3', toy_id: '3', image_url: '', display_order: 0 }],
    owner: {
      id: 'user-3',
      username: 'alice_wang',
      avatar_url: null,
      display_name: '王阿姨',
      latitude: 39.8942,
      longitude: 116.3974,
      location_name: '北京市海淀区',
      credit_balance: 200,
      locale: 'zh',
      created_at: '2026-03-20T00:00:00Z',
    },
  },
  {
    id: '4',
    owner_id: 'user-4',
    title: '奥特曼变身器 戴拿奥特曼',
    description: '全新未拆封，孩子收到了两个一样的，分享一个给其他小朋友。',
    category: 'figures' as ToyCategory,
    age_range: '3-6' as AgeRange,
    condition: 'new' as ToyCondition,
    estimated_value: 45,
    status: 'available',
    is_cleaned: false,
    latitude: 39.9242,
    longitude: 116.4274,
    created_at: '2026-05-04T16:00:00Z',
    updated_at: '2026-05-04T16:00:00Z',
    images: [{ id: 'img-4', toy_id: '4', image_url: '', display_order: 0 }],
    owner: {
      id: 'user-4',
      username: 'super_dad',
      avatar_url: null,
      display_name: '超级爸爸',
      latitude: 39.9242,
      longitude: 116.4274,
      location_name: '北京市朝阳区望京',
      credit_balance: 45,
      locale: 'zh',
      created_at: '2026-04-10T00:00:00Z',
    },
  },
  {
    id: '5',
    owner_id: 'user-5',
    title: '儿童滑板车 可折叠三轮',
    description: '适合3-8岁，可调节高度。轮子有LED灯。有一些使用痕迹但不影响骑行。',
    category: 'outdoor' as ToyCategory,
    age_range: '3-6' as AgeRange,
    condition: 'used' as ToyCondition,
    estimated_value: 50,
    status: 'available',
    is_cleaned: true,
    latitude: 39.8842,
    longitude: 116.4374,
    created_at: '2026-05-05T11:00:00Z',
    updated_at: '2026-05-05T11:00:00Z',
    images: [{ id: 'img-5', toy_id: '5', image_url: '', display_order: 0 }],
    owner: {
      id: 'user-5',
      username: 'outdoor_fan',
      avatar_url: null,
      display_name: '运动达人',
      latitude: 39.8842,
      longitude: 116.4374,
      location_name: '北京市丰台区',
      credit_balance: 150,
      locale: 'zh',
      created_at: '2026-04-15T00:00:00Z',
    },
  },
  {
    id: '6',
    owner_id: 'user-6',
    title: 'Switch 马里奥赛车实体卡带',
    description: '孩子通关了不想再玩。卡带完好无划痕。',
    category: 'electronic' as ToyCategory,
    age_range: '6-9' as AgeRange,
    condition: 'like_new' as ToyCondition,
    estimated_value: 100,
    status: 'available',
    is_cleaned: false,
    latitude: 39.9342,
    longitude: 116.3874,
    created_at: '2026-05-06T08:00:00Z',
    updated_at: '2026-05-06T08:00:00Z',
    images: [{ id: 'img-6', toy_id: '6', image_url: '', display_order: 0 }],
    owner: {
      id: 'user-6',
      username: 'gamer_li',
      avatar_url: null,
      display_name: '李小游',
      latitude: 39.9342,
      longitude: 116.3874,
      location_name: '北京市西城区',
      credit_balance: 90,
      locale: 'zh',
      created_at: '2026-04-20T00:00:00Z',
    },
  },
];
